# WARNING: Do not deploy this tutorial configuration directly to a production environment
#
# The tutorial docker-compose files have not been written for production deployment and will not 
# scale. A proper architecture has been sacrificed to keep the narrative focused on the learning 
# goals, they are just used to deploy everything onto a single Docker machine. All FIWARE components 
# are running at full debug and extra ports have been exposed to allow for direct calls to services. 
# They also contain various obvious security flaws - passwords in plain text, no load balancing,
# no use of HTTPS and so on. 
# 
# This is all to avoid the need of multiple machines, generating certificates, encrypting secrets
# and so on, purely so that a single docker-compose file can be read as an example to build on, 
# not use directly. 
# 
# When deploying to a production environment, please looking at the SmartSDK Recipes
# in order to scale up to a proper architecture:
# 
# see: https://smartsdk.github.io/smartsdk-recipes/
#
# en producción debería de tener en cuenta de que debe haber cargado mongo-db antes que orion.
version: "3.5"
services:
  # Orion is the context broker
  orion:
    image: fiware/orion:${ORION_VERSION}
    hostname: orion
    container_name: fiware-orion-tutorial
    depends_on:
      - mongo-db
    networks:
      - fiware
    ports:
      - "${ORION_PORT}:${ORION_PORT}" # localhost:1026
    command: -dbhost mongo-db -logLevel DEBUG -noCache #connect to the mogno database opcion que se añade
    healthcheck:
      test: curl --fail -s http://orion:${ORION_PORT}/version || exit 1


  # Databases
  mongo-db:
    image: mongo:${MONGO_DB_VERSION}
    hostname: mongo-db
    container_name: db-mongo-tutorial
    expose:
      - "${MONGO_DB_PORT}"
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}" # localhost:27017 # localhost:27017
    networks:
      - fiware
    command: --bind_ip_all --smallfiles #se pueden conectar por cualquier ip de la maquina no solo desde localhost
    volumes:
      - mongo-db-tutorial:/data
  
  # Web Client
  web-client:
    build:
      context: ./web-client
    hostname: web-client
    container_name: web-client-tutorial
    depends_on:
      - orion
    expose: 
      - "${WEB_CLIENT_PORT}"
    ports:
      - "${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}"
    networks:
      - fiware
    environment:
      - "WEB_CLIENT_PORT=${WEB_CLIENT_PORT}"
      - "CONTEXT_BROKER=${CONTEXT_BROKER}"
      - "NGSI_VERSION=${NGSI_VERSION}"

  # Draco
    # Draco is configured to write context data to Mongo-DB
  draco:
    image: ging/fiware-draco:${DRACO_VERSION}
    hostname: draco
    container_name: fiware-draco-tutorial
    networks:
      - fiware
    environment:
      - NIFI_WEB_HTTP_PORT=${DRACO_API_PORT}
    expose:
      - "5050"
      - "${DRACO_API_PORT}"
    ports:
      - "${DRACO_API_PORT}:${DRACO_API_PORT}" # localhost:9090
      - "5050:5050"
    healthcheck:
      test: curl --fail -s http://draco:${DRACO_API_PORT}/nifi-api/system-diagnostics || exit 1
      start_period: 1m
networks:
  fiware:
    ipam:
      config:
        - subnet: 172.18.1.0/24
volumes:
  mongo-db-tutorial:
