# WARNING: Do not deploy this tutorial configuration directly to a production environment
#
# The tutorial docker-compose files have not been written for production deployment and will not 
# scale. A proper architecture has been sacrificed to keep the narrative focused on the learning 
# goals, they are just used to deploy everything onto a single Docker machine. All FIWARE components 
# are running at full debug and extra ports have been exposed to allow for direct calls to services. 
# They also contain various obvious security flaws - passwords in plain text, no load balancing,
# no use of HTTPS and so on. 
# 
# This is all to avoid the need of multiple machines, generating certificates, encrypting secrets
# and so on, purely so that a single docker-compose file can be read as an example to build on, 
# not use directly. 
# 
# When deploying to a production environment, please looking at the SmartSDK Recipes
# in order to scale up to a proper architecture:
# 
# see: https://smartsdk.github.io/smartsdk-recipes/
#
# en producción debería de tener en cuenta de que debe haber cargado mongo-db antes que orion.
version: "3.5"
services:
  # Orion is the context broker
  orion:
    image: fiware/orion:${ORION_VERSION}
    hostname: orion
    container_name: fiware-orion-tutorial
    depends_on:
      - mongo-db
    networks:
      - fiware
    ports:
      - "${ORION_PORT}:${ORION_PORT}" # localhost:1026
    command: -dbhost mongo-db -logLevel DEBUG -noCache #connect to the mogno database opcion que se añade
    healthcheck:
      test: curl --fail -s http://orion:${ORION_PORT}/version || exit 1

  # Databases
    # For orion
  mongo-db:
    restart: always
    image: mongo:${MONGO_DB_VERSION}
    hostname: mongo-db
    container_name: db-mongo-tutorial
    expose:
      - "${MONGO_DB_PORT}"
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}" # localhost:27017 # localhost:27017
    networks:
      - fiware
    command: --bind_ip_all --smallfiles #se pueden conectar por cualquier ip de la maquina no solo desde localhost
    volumes:
      - mongo-db-tutorial:/data
    # For keyrock
  mysql-db:
    restart: always
    image: mysql:${MYSQL_DB_VERSION}
    hostname: mysql-db
    container_name: db-mysql-tutorial
    expose:
        - "${MYSQL_DB_PORT}"
    ports:
        - "${MYSQL_DB_PORT}:${MYSQL_DB_PORT}"
    networks:
      fiware:
        ipv4_address: 172.18.1.6
    environment:
        - "MYSQL_ROOT_PASSWORD=${IDM_DB_PASS}"
        - "MYSQL_ROOT_HOST=172.18.1.5" # allow connections from this ip
    volumes:
        - mysql-db-tutorial:/var/lib/mysql
  # Web Client
  web-client:
    build:
      context: ./web-client
    hostname: web-client
    container_name: web-client-tutorial
    depends_on:
      - orion
    expose: 
      - "${WEB_CLIENT_PORT}"
    ports:
      - "${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}"
    networks:
      - fiware
    environment:
      - "WEB_CLIENT_PORT=${WEB_CLIENT_PORT}"
      - "CONTEXT_BROKER=${CONTEXT_BROKER}"
      - "NGSI_VERSION=${NGSI_VERSION}"
  # keyrock
  keyrock:
    image: fiware/idm:${KEYROCK_VERSION}
    container_name: fiware-keyrock-tutorial
    hostname: keyrock
    depends_on:
        - mysql-db
    ports:
      - "${KEYROCK_PORT}:${KEYROCK_PORT}" # HTTP
      - "${KEYROCK_HTTPS_PORT}:${KEYROCK_HTTPS_PORT}" # HTTPS
    networks:
      fiware:
        ipv4_address: 172.18.1.5
    environment:
        - "DEBUG=idm:*"
        - "IDM_DB_HOST=mysql-db"
        - "IDM_DB_PASS=${IDM_DB_PASS}"
        - "IDM_DB_USER=root"
        - "IDM_HOST=${IDM_HOST}:${KEYROCK_PORT}"
        - "IDM_PORT=${KEYROCK_PORT}"
        - "IDM_HTTPS_ENABLED=${IDM_HTTPS_ENABLED}"
        - "IDM_HTTPS_PORT=${KEYROCK_HTTPS_PORT}"
        - "IDM_ADMIN_USER=${IDM_ADMIN_USER}"
        - "IDM_ADMIN_EMAIL=${IDM_ADMIN_EMAIL}"
        - "IDM_ADMIN_PASS=${IDM_ADMIN_PASS}"
    healthcheck:
      test: curl --fail -s http://keyrock:${KEYROCK_PORT}/version || exit 1
    
networks:
  fiware:
    ipam:
      config:
        - subnet: 172.18.1.0/24

volumes:
  mongo-db-tutorial:
  mysql-db-tutorial:
